[package]
name = "notes"
version = "0.1.0"
authors = ["swj"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0"
serde_derive = "1.0"
pulldown-cmark = "0.1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]